# Site settings
title: Soapie - Make the internet more visible
email: soapie.tool@protonmail.com
description: >
  Soapie is an open-source browser extension (support Mozilla Firefox and Google Chrome) to make the internet more accessible for people who are sight impaired. We aim to use the cutting edge AI technology to fill in the blanks of a webpage (e.g. missing alt tag) or remove blocks to improve browsing experience for people in need. When installed and switched on, Soapie will automatically change the html of the webpage so it can be easily accessible for other assisting tools.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: soapie_tool
github_username: soapie-tool

# Build settings
markdown: kramdown
